#!/bin/bash

source "$(dirname "$0")/config"

if [ "$1" == "stop" ]; then
	if [ -e /dev/shm/mplayer-pid ]; then
		if ! kill "$(<"$MP_PID")"; then
			echo "Failed to kill mplayer."
			exit 2
		fi
	else
		echo "Can't find $MP_PID ."
		exit 3
	fi
else
	[ -p "$MP_CONTROL" ] || mkfifo "$MP_CONTROL"
	[ -p "$MP_OUTPUT" ] || mkfifo "$MP_OUTPUT"
	
	mplayer -quiet -slave -input file="$MP_CONTROL" -idle > "$MP_OUTPUT" 2> "$MP_ERROR" &
	echo "$!" > "$MP_PID"
fi
